disabled_rules:
  - force_cast
  - line_length
  - trailing_whitespace
  - nesting
  - opening_brace
  - valid_docs
excluded:
  - Sources/Container.Arguments.swift
  - Sources/SynchronizedResolver.Arguments.swift
  - Sources/ResolverType.swift
  - Tests
  - Sample-iOS.playground
  - Carthage

variable_name:
  min_length:
    warning: 1
    error: 1
