name: Swinject
options:
  bundleIdPrefix: com.el-eleven
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  deploymentTarget:
    macOS: '10.10'
    tvOS: '9.0'
    iOS: '9.0'
    watchOS: '2.0'
settingGroups:
      macOS:
        EXCLUDED_ARCHS: ''
      iOS:
        EXCLUDED_ARCHS[sdk=iphonesimulator*]: 'arm64'
      tvOS:
        EXCLUDED_ARCHS[sdk=appletvsimulator*]: 'arm64'
      watchOS:
        EXCLUDED_ARCHS: ''
targets:
  Swinject:
    type: framework
    platform: [macOS, iOS, tvOS, watchOS]
    platformSuffix: -${platform}
    settings:
      base:
        APPLICATION_EXTENSION_API_ONLY: 'YES'
      groups:
        - ${platform}
    scheme:
      testTargets:
        - SwinjectTests-${platform}
    sources:
      - path: Sources
        excludes: ["*.erb"]
    postCompileScripts:
      - script: >
          if which swiftlint >/dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
        name: Swiftlint
  SwinjectTests:
    type: bundle.unit-test
    platform: [macOS, iOS, tvOS, watchOS]
    platformSuffix: -${platform}
    scheme: {}
    sources:
      - Tests/SwinjectTests
    dependencies:
      - target: Swinject-${platform}
      - carthage: Quick
      - carthage: Nimble
