#!/bin/sh

files="Sources/Container.Arguments Sources/SynchronizedResolver.Arguments Sources/Resolver Sources/ServiceEntry.TypeForwarding"

for file in $files; do
  echo "Generating code to $file.swift"
  erb -v -T 1 $file.erb > $file.swift
done
