# This is the First Workflow for Testing with Github Actions

name: Pod Lint
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  ENCODING: LC_CTYPE=en_US.UTF-8
jobs:
  pod-lint:
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Linting PodSpec for Cocoapods
        run: export "${{ env. ENCODING }}" | pod lib lint --platforms=ios,macos,watchos
        shell: bash
